### ISSUE TITLE
existing notebook

### ISSUE THREAD

**Issue by alecloudenback** [actuarialopensource/experience_studies_R_Julia#1]
I don't remember if I shared this with you, but it's replicating the analysis in the actexp README:

https://github.com/JuliaActuary/Learn/blob/master/actexp_analysis.jl

**Comment by MatthewCaseres** [comment]
You did! I am always amazed at how quickly you are able to send me code when I am doing Julia things.

The analysis should be complete and has identified several bugs in both packages. http://htmlpreview.github.io/?https://github.com/actuarialopensource/experience_studies_R_Julia/blob/main/analysis.html
